/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct image {
	struct {
		u_int buffer_len;
		char *buffer_val;
	} buffer;
};
typedef struct image image;

#define MINIFY_PROG 0x31230000
#define MINIFY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFY_IMAGE 1
extern  enum clnt_stat minify_image_1(image , image *, CLIENT *);
extern  bool_t minify_image_1_svc(image , image *, struct svc_req *);
extern int minify_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFY_IMAGE 1
extern  enum clnt_stat minify_image_1();
extern  bool_t minify_image_1_svc();
extern int minify_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_image (XDR *, image*);

#else /* K&R C */
extern bool_t xdr_image ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
